artifacts_dir: artifacts/
data:
  dataloader:
    batch_size: 64
    max_length: 80
    min_length: 80
  dataset:
    concat_input: true
    concat_output: true
    input_dims:
      bex_20230623_denoised:
        poses: 34
      ken_20230614_denoised:
        poses: 45
      ken_20230618_denoised:
        poses: 41
    input_modalities:
    - poses
    output_dims:
      bex_20230623_denoised:
        location: 2
      ken_20230614_denoised:
        location: 2
      ken_20230618_denoised:
        location: 2
    output_modalities:
    - location
    stride: 20
  dir: data
  intervals:
    balance_intervals: false
    include_homing: true
    include_sitting: true
    include_trial: true
  modalities:
    kinematics:
      representation: com_vec
    location:
      representation: com
    poses:
      coordinates: egocentric
      project_to_pcs: medium
      representation: medium
      skeleton_type: normal
    spike_count:
      brain_areas: all
    spikes:
      brain_areas: all
  sampling_rate: 20
experiment: old_gbyk
logger:
  dir: artifacts/poses_to_location/20250820210428
  plots: false
model:
  architecture: embedding_core_readout
  core:
    architecture: fc
    dims: 128
    n_layers: 3
  embedding:
    architecture:
      bex_20230623_denoised:
        poses: linear
      ken_20230614_denoised:
        poses: linear
      ken_20230618_denoised:
        poses: linear
    dim: 128
  readout:
    map:
      bex_20230623_denoised:
        location: linear
      ken_20230614_denoised:
        location: linear
      ken_20230618_denoised:
        location: linear
save: true
seed: 0
sessions:
- bex_20230623_denoised
- ken_20230614_denoised
- ken_20230618_denoised
task: poses_to_location
trainer:
  early_stopper:
    enabled: true
  loss_fns:
    location: mse
  max_epochs: 10000
  metrics:
    location: rmse
  optimizer:
    algorithm: adam
    lr: 0.001
    weight_decay: 1.0e-05
  scheduler:
    T_max: 100
    eta_min: 0.0001
    method: cosine_annealing
  validation_frequency: 25
uid: '20250820210428'
